version: "3.9"
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/nextjs.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public
      - ./next.config.js:/app/next.config.js
    depends_on:
      - nextjs
